export const DATA: any[] = [
  { firstName: 'Martin', lastName: 'Apostolov', age: 15 },
  { firstName: 'Sulio', lastName: 'Puliov', age: 23 },
  { firstName: 'Yordan', lastName: 'Petrov', age: 5 },
  { firstName: 'Georgi', lastName: 'Dragnev', age: 12 },
  { firstName: 'Pavel', lastName: 'Stoqnov', age: 56 },
  { firstName: 'Petar', lastName: 'Pavlov', age: 17 },
  { firstName: 'Alex', lastName: 'Stefanov', age: 17 },
  { firstName: 'Georgi', lastName: 'Antonov', age: 64 },
  { firstName: 'Martin', lastName: 'Apostolov', age: 15 },
  { firstName: 'Sulio', lastName: 'Puliov', age: 23 },
  { firstName: 'Yordan', lastName: 'Petrov', age: 5 },
  { firstName: 'Georgi', lastName: 'Dragnev', age: 12 },
  { firstName: 'Pavel', lastName: 'Stoqnov', age: 56 },
  { firstName: 'Petar', lastName: 'Pavlov', age: 17 },
  { firstName: 'Alex', lastName: 'Stefanov', age: 17 },
  { firstName: 'Georgi', lastName: 'Antonov', age: 64 },
  { firstName: 'georgi', lastName: 'antonov', age: 63 },
];
